services:
  Evrinoma\HeaderBundle\Controller\HeaderApiController:
    alias: evrinoma.header.api.controller
    public: true

  evrinoma.header.api.controller:
    class: Evrinoma\HeaderBundle\Controller\HeaderApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.header.query.manager'
    autowire: true

  evrinoma.header.query.manager:
    class: Evrinoma\HeaderBundle\Manager\QueryManager
    arguments:
      - '@evrinoma.header.repository'

  Evrinoma\HeaderBundle\Manager\QueryManager:
    alias: evrinoma.header.query.manager

  evrinoma.header.repository:
    class: Evrinoma\HeaderBundle\Repository\HeaderRepository
    public: true
    arguments:
